# Generated by Django 5.2.8 on 2025-12-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=10)),
            ],
        ),
    ]
