# Generated by Django 5.2.8 on 2025-12-02 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('Espèce', 'Espèce'), ('Carte', 'Carte'), ('Virement', 'Virement')], max_length=20)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contrat')),
            ],
        ),
    ]
