# Generated by Django 5.2.8 on 2025-12-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_rename_contrat_contract'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paiement',
            new_name='Payment',
        ),
    ]
