# Generated by Django 5.2.8 on 2025-12-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('prix_journalier', models.DecimalField(decimal_places=2, max_digits=8)),
                ('etat', models.CharField(choices=[('Disponible', 'Disponible'), ('Louée', 'Louée'), ('Maintenance', 'Maintenance')], max_length=20)),
                ('kilometrage', models.IntegerField()),
            ],
        ),
    ]
