# Generated by Django 5.2.9 on 2025-12-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_contract_vehicule'),
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='id_contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
    ]
