# Generated by Django 5.2.9 on 2025-12-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_vehicule_id_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='id_contrat',
        ),
    ]
