# Generated by Django 5.2.8 on 2025-12-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('client', '0001_initial'),
        ('contract', '0001_initial'),
        ('payment', '0001_initial'),
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contrat',
            new_name='Contract',
        ),
    ]
