# Generated by Django 5.2.9 on 2025-12-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_rename_contrat_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='vehicule',
        ),
    ]
